import { listChannelPlugins } from "../channels/plugins/index.js";

const BASE_METHODS = [
  "health",
  "doctor.findings",
  "logs.tail",
  "channels.status",
  "channels.logout",
  "channels.update",
  "channels.validate",
  "channels.configure",
  "status",
  "usage.status",
  "usage.cost",
  "tts.status",
  "tts.providers",
  "tts.enable",
  "tts.disable",
  "tts.convert",
  "tts.setProvider",
  "config.get",
  "config.set",
  "config.apply",
  "config.patch",
  "config.schema",
  "exec.approvals.get",
  "exec.approvals.set",
  "exec.approvals.node.get",
  "exec.approvals.node.set",
  "exec.approval.request",
  "exec.approval.waitDecision",
  "exec.approval.resolve",
  "wizard.start",
  "wizard.next",
  "wizard.cancel",
  "wizard.status",
  "talk.config",
  "talk.mode",
  "models.list",
  "models.auth.list",
  "models.auth.test",
  "models.auth.set",
  "models.auth.delete",
  "models.setDefault",
  "agents.list",
  "agents.create",
  "agents.update",
  "agents.delete",
  "agents.files.list",
  "agents.files.get",
  "agents.files.set",
  "skills.status",
  "skills.bins",
  "skills.install",
  "skills.crystallize",
  "skills.network",
  "skills.networkHistory",
  "skills.update",
  "skills.create",
  "skills.manage",
  "skills.promote",
  "skills.rollback",
  "skills.evolution.status",
  "skills.evolution.corpus.list",
  "skills.evolution.corpus.accept",
  "skills.evolution.corpus.reject",
  "skills.evolution.feedback",
  "skills.evolution.probe",
  "skills.evolution.routing.repair",
  "skills.incoming.list",
  "skills.incoming.accept",
  "skills.incoming.reject",
  "update.run",
  "update.check",
  "system.restart",
  "system.shutdown",
  "voicewake.get",
  "voicewake.set",
  "sessions.list",
  "sessions.preview",
  "sessions.patch",
  "sessions.reset",
  "sessions.delete",
  "sessions.compact",
  "last-heartbeat",
  "set-heartbeats",
  "wake",
  "node.pair.request",
  "node.pair.list",
  "node.pair.approve",
  "node.pair.reject",
  "node.pair.verify",
  "device.pair.list",
  "device.pair.approve",
  "device.pair.reject",
  "device.token.rotate",
  "device.token.revoke",
  "node.rename",
  "node.list",
  "node.describe",
  "node.invoke",
  "node.invoke.result",
  "node.event",
  "cron.list",
  "cron.status",
  "cron.add",
  "cron.update",
  "cron.remove",
  "cron.run",
  "cron.runs",
  "system-presence",
  "system-event",
  "send",
  "agent",
  "agent.identity.get",
  "agent.runtime.health",
  "agent.wait",
  "browser.request",
  // WebChat WebSocket-native chat methods
  "chat.history",
  "chat.abort",
  "chat.send",
  // Projects
  "projects.list",
  "projects.get",
  "projects.create",
  "projects.update",
  "projects.delete",
  "projects.files.list",
  "projects.files.upload",
  "projects.files.delete",
  "projects.context",
  // Dream Engine
  "dream.status",
  "dream.history",
  "dream.insights",
  "dream.trigger",
  "dream.emotional",
  "dream.analytics",
  "dream.journal",
  "dream.suggestSkills",
  "dream.marketplaceStatus",
  "dream.curiosityReward",
  // PLAN-28 B4: retrieval-layer health
  "memory.retrievalHealth",
  // PLAN-29 Phase 3: Forage spectator layer
  "forage.tape",
  "forage.stats",
  // PLAN-29 §4.1: operator posting path
  "forage.post",
  // PLAN-30 G0.5: judge-capped settlement review
  "forage.review",
  "forage.reviewRelease",
  // PLAN-31 C1/C2: circles — the connection graph (gated by circles.enabled, ON by default)
  "circles.status",
  "circles.list",
  "circles.create",
  "circles.invite",
  "circles.join",
  "circles.send",
  "circles.messages",
  "circles.tab.add",
  "circles.tab.balances",
  "circles.sync",
  "circles.ask",
  "circles.disclosure.set",
  "circles.disclosure.list",
  "circles.briefing",
  // Marketplace
  "marketplace.search",
  "marketplace.trending",
  "marketplace.recommendations",
  "marketplace.detail",
  "marketplace.listForSale",
  "marketplace.delist",
  "marketplace.commerce",
  "marketplace.bonds",
  "marketplace.contributors",
  "marketplace.contributorClearFlag",
  "marketplace.postBond",
  // Management
  "management.census",
  "management.anomalies",
  "management.health",
  "management.economics",
  "management.censusHistory",
  "management.propagateBan",
  // Wallet
  "wallet.getAddress",
  "wallet.getBalance",
  "wallet.getHistory",
  "wallet.getConfig",
  "wallet.setConfig",
  "wallet.fund",
  "wallet.x402Pay",
  "wallet.stripeOnramp",
];

export function listGatewayMethods(): string[] {
  const channelMethods = listChannelPlugins().flatMap((plugin) => plugin.gatewayMethods ?? []);
  return Array.from(new Set([...BASE_METHODS, ...channelMethods]));
}

export const GATEWAY_EVENTS = [
  "connect.challenge",
  "agent",
  "artifact",
  "chat",
  "presence",
  "tick",
  "talk.mode",
  "shutdown",
  "health",
  "heartbeat",
  "cron",
  "node.pair.requested",
  "node.pair.resolved",
  "node.invoke.request",
  "device.pair.requested",
  "device.pair.resolved",
  "voicewake.changed",
  "exec.approval.requested",
  "exec.approval.resolved",
  // PLAN-36 Phase 0: inbound circle message/ask/answer arrived (direct dial or
  // mailbox drain) — the People pane refreshes on this instead of polling.
  "circles",
  // Periodic update-staleness status (git behind count / npm version drift);
  // the Control UI raises or clears its update prompt on this.
  "update",
];
