/**
 * PLAN-45 Phase 2.1 (D-5): CANONICAL CAPABILITY generator families.
 *
 * The regression templates (canonical-corpus.ts) are near-ceiling by design
 * and cannot detect improvement. Until now the promotion signal lived only
 * in the node's grown corpus, so a fresh node could never reach tasks mode
 * (validation-mode.ts needs >= 5 capability tasks) and every proposal HELD.
 *
 * These families are PROCEDURAL, multi-step tasks over generated files in
 * the trial workspace: the agent has to look, run, count, edit, and report
 * one exact value. Each `template(rng) -> (task, truth)` is seeded exactly
 * like the regression templates (fresh instance per validation; a
 * memorized answer buys nothing) and every checker is the hardened `final`
 * kind. The files ride on the task (`files`) and the runtime-pathway
 * runner writes them into the scratch workspace before the turn.
 *
 * Difficulty: every family ships at one calibrated difficulty; the gate's
 * per-model calibration (trial-cache task stats) drops a family for a model
 * that always passes (> 0.8) or never passes (< 0.2) it, so the suite that
 * feeds the sign test is the one that carries information for THIS model.
 *
 * Updating a family = a new generator version (canonical-corpus.ts
 * CANONICAL_GENERATOR_VERSION + exemplar pin), same release act as the
 * regression templates.
 */

import type { CorpusTask } from "./task-corpus.js";

export const CAPABILITY_TAG = "capability";
export const CANONICAL_TAG = "canonical";
/** Total generated bytes per task (all files together) and file count per task. */
export const MAX_TASK_FILE_BYTES = 64 * 1024;
export const MAX_TASK_FILES = 20;

type Rng = () => number;

function int(rng: Rng, lo: number, hi: number): number {
  return lo + Math.floor(rng() * (hi - lo + 1));
}
function pick<T>(rng: Rng, arr: readonly T[]): T {
  return arr[Math.floor(rng() * arr.length)] as T;
}
function shuffle<T>(rng: Rng, arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j] as T, a[i] as T];
  }
  return a;
}

const NAMES = [
  "alpha",
  "bravo",
  "cedar",
  "dune",
  "ember",
  "falcon",
  "glacier",
  "harbor",
  "iris",
  "jasper",
  "kestrel",
  "lagoon",
  "meadow",
  "nimbus",
  "orchid",
  "pixel",
] as const;
const SERVICES = [
  "auth",
  "billing",
  "cache",
  "gateway",
  "indexer",
  "mailer",
  "search",
  "worker",
] as const;
const REGIONS = ["east", "west", "north", "south"] as const;
const STATUSES = ["shipped", "pending", "returned", "cancelled"] as const;

const FINAL = 'Reply with exactly one line of the form "FINAL: <answer>".';

function capTask(
  family: string,
  prompt: string,
  answer: string,
  files: Record<string, string>,
  extraTags: string[] = [],
): CorpusTask {
  return {
    id: `cap-${family}`,
    prompt: `${prompt} ${FINAL}`,
    checker: { kind: "final", value: answer },
    tags: [CAPABILITY_TAG, CANONICAL_TAG, family, ...extraTags],
    suite: "capability",
    files,
    timeoutMs: 180_000,
  };
}

// ---------------------------------------------------------------------------
// Families
// ---------------------------------------------------------------------------

export const CAPABILITY_TEMPLATES: Array<(rng: Rng) => CorpusTask> = [
  // 1. ledger-sum: sum the amounts for one account across a CSV with decoys
  //    and negative entries.
  (rng) => {
    const accounts = shuffle(rng, [...NAMES]).slice(0, 5);
    const target = accounts[0] as string;
    const rows: string[] = ["date,account,amount"];
    let total = 0;
    const n = int(rng, 24, 40);
    for (let i = 0; i < n; i++) {
      const acct = pick(rng, accounts);
      const amount = int(rng, -250, 900);
      if (acct === target) {
        total += amount;
      }
      rows.push(`2026-0${int(rng, 1, 9)}-${String(int(rng, 10, 28))},${acct},${amount}`);
    }
    return capTask(
      "ledger-sum",
      `The file data/ledger.csv in your workspace has columns date,account,amount. Compute the net total of the amount column for the account "${target}" (amounts can be negative). Report the integer.`,
      String(total),
      { "data/ledger.csv": `${rows.join("\n")}\n` },
      ["files", "exec"],
    );
  },
  // 2. log-triage: which service logged the most ERROR lines, and how many.
  (rng) => {
    const svcs = shuffle(rng, [...SERVICES]).slice(0, 5);
    const counts = new Map<string, number>();
    const lines: string[] = [];
    const n = int(rng, 60, 110);
    for (let i = 0; i < n; i++) {
      const svc = pick(rng, svcs);
      const level = rng() < 0.3 ? "ERROR" : rng() < 0.5 ? "WARN" : "INFO";
      if (level === "ERROR") {
        counts.set(svc, (counts.get(svc) ?? 0) + 1);
      }
      lines.push(
        `2026-09-05T${String(int(rng, 0, 23)).padStart(2, "0")}:${String(int(rng, 0, 59)).padStart(2, "0")}:00Z ${level} ${svc}: ${level === "ERROR" ? "request failed" : "ok"} id=${int(rng, 1000, 9999)}`,
      );
    }
    // Force a unique maximum.
    const sorted = [...counts.entries()].toSorted((a, b) => b[1] - a[1]);
    const [top, topCount] = sorted[0] ?? [svcs[0] as string, 0];
    const runnerUp = sorted[1]?.[1] ?? -1;
    let finalCount = topCount;
    if (runnerUp === topCount) {
      lines.push(`2026-09-05T23:59:00Z ERROR ${top}: request failed id=1`);
      finalCount += 1;
    }
    return capTask(
      "log-triage",
      `The file logs/app.log in your workspace has one entry per line of the form "<timestamp> <LEVEL> <service>: <message>". Which service has the most ERROR-level lines, and how many does it have? Answer as "<service>:<count>".`,
      `${top}:${finalCount}`,
      { "logs/app.log": `${shuffle(rng, lines).join("\n")}\n` },
      ["files", "exec"],
    );
  },
  // 3. config-diff: keys whose values differ between two flat JSON configs.
  (rng) => {
    const keys = shuffle(rng, [...NAMES]).slice(0, 12);
    const base: Record<string, unknown> = {};
    const prod: Record<string, unknown> = {};
    const differing: string[] = [];
    for (const k of keys) {
      const v = int(rng, 1, 500);
      base[k] = v;
      if (rng() < 0.35) {
        prod[k] = v + int(rng, 1, 9);
        differing.push(k);
      } else {
        prod[k] = v;
      }
    }
    if (differing.length === 0) {
      const k = keys[0] as string;
      prod[k] = (base[k] as number) + 1;
      differing.push(k);
    }
    return capTask(
      "config-diff",
      `Compare config/base.json and config/prod.json in your workspace (flat JSON objects with the same keys). Report the keys whose values differ, sorted alphabetically, comma-separated with no spaces.`,
      differing.toSorted().join(","),
      {
        "config/base.json": `${JSON.stringify(base, null, 2)}\n`,
        "config/prod.json": `${JSON.stringify(prod, null, 2)}\n`,
      },
      ["files"],
    );
  },
  // 4. dep-depth: transitive dependency count of one package in a DAG.
  (rng) => {
    const pkgs = shuffle(rng, [...NAMES]).slice(0, 9);
    const deps: Record<string, string[]> = {};
    // Edges only point to later packages: guaranteed acyclic.
    for (let i = 0; i < pkgs.length; i++) {
      const later = pkgs.slice(i + 1);
      // The root always has at least one edge so "0" is never a free guess.
      const k = Math.min(later.length, i === 0 ? int(rng, 1, 3) : int(rng, 0, 3));
      deps[pkgs[i] as string] = shuffle(rng, later).slice(0, k).toSorted();
    }
    const root = pkgs[0] as string;
    const seen = new Set<string>();
    const walk = (p: string) => {
      for (const d of deps[p] ?? []) {
        if (!seen.has(d)) {
          seen.add(d);
          walk(d);
        }
      }
    };
    walk(root);
    return capTask(
      "dep-depth",
      `The file deps.json in your workspace maps each package to the list of packages it depends on directly. How many DISTINCT packages does "${root}" depend on transitively (direct and indirect, not counting itself)? Report the integer.`,
      String(seen.size),
      { "deps.json": `${JSON.stringify(deps, null, 2)}\n` },
      ["files", "reasoning"],
    );
  },
  // 5. regex-valid: count the lines matching a described format among decoys.
  (rng) => {
    const lines: string[] = [];
    let valid = 0;
    const n = int(rng, 30, 60);
    for (let i = 0; i < n; i++) {
      const letters = Array.from({ length: 3 }, () =>
        String.fromCharCode(65 + int(rng, 0, 25)),
      ).join("");
      const digits = String(int(rng, 0, 9999)).padStart(4, "0");
      const roll = rng();
      if (roll < 0.45) {
        lines.push(`${letters}-${digits}`);
        valid += 1;
      } else if (roll < 0.6) {
        lines.push(`${letters.toLowerCase()}-${digits}`);
      } else if (roll < 0.75) {
        lines.push(`${letters}-${digits.slice(0, 3)}`);
      } else if (roll < 0.9) {
        lines.push(`${letters}${digits}`);
      } else {
        lines.push(`${letters}-${digits}-x`);
      }
    }
    return capTask(
      "regex-valid",
      `The file data/ids.txt in your workspace has one identifier per line. A VALID identifier is exactly three uppercase ASCII letters, a hyphen, and exactly four digits, with nothing else on the line. How many lines are valid? Report the integer.`,
      String(valid),
      { "data/ids.txt": `${lines.join("\n")}\n` },
      ["files", "exec"],
    );
  },
  // 6. multi-file-rename: rename an identifier across files and count edits.
  (rng) => {
    const oldName = `${pick(rng, NAMES)}_handler`;
    const newName = `${pick(rng, NAMES)}_service`;
    const decoy = `${oldName}_legacy`;
    const files: Record<string, string> = {};
    let total = 0;
    const fileCount = int(rng, 3, 5);
    for (let f = 0; f < fileCount; f++) {
      const lines: string[] = [];
      const occurrences = int(rng, 0, 4);
      for (let i = 0; i < occurrences; i++) {
        lines.push(`result = ${oldName}(request_${i})`);
      }
      if (rng() < 0.6) {
        lines.push(`legacy = ${decoy}(request)`);
      }
      lines.push(`log("done ${f}")`);
      total += occurrences;
      files[`src/module_${f}.py`] = `${shuffle(rng, lines).join("\n")}\n`;
    }
    if (total === 0) {
      files["src/module_0.py"] =
        `result = ${oldName}(request_0)\n${files["src/module_0.py"] ?? ""}`;
      total = 1;
    }
    return capTask(
      "multi-file-rename",
      `Under src/ in your workspace, rename every whole-word occurrence of the identifier ${oldName} to ${newName} in every file (do not touch ${decoy}, which is a different identifier). Then report how many occurrences you replaced in total. Report the integer.`,
      String(total),
      files,
      ["files", "exec", "edit"],
    );
  },
  // 7. csv-filter-sum: sum a column under two filters.
  (rng) => {
    const region = pick(rng, REGIONS);
    const rows = ["order_id,region,status,qty"];
    let sum = 0;
    const n = int(rng, 30, 50);
    for (let i = 0; i < n; i++) {
      const r = pick(rng, REGIONS);
      const s = pick(rng, STATUSES);
      const qty = int(rng, 1, 40);
      if (r === region && s === "shipped") {
        sum += qty;
      }
      rows.push(`${1000 + i},${r},${s},${qty}`);
    }
    return capTask(
      "csv-filter-sum",
      `The file data/orders.csv in your workspace has columns order_id,region,status,qty. What is the sum of qty over rows where region is "${region}" AND status is "shipped"? Report the integer.`,
      String(sum),
      { "data/orders.csv": `${rows.join("\n")}\n` },
      ["files", "exec"],
    );
  },
  // 8. json-path: extract a value at a nested path with array indexing.
  (rng) => {
    const items = Array.from({ length: int(rng, 3, 6) }, (_, i) => ({
      id: i,
      name: pick(rng, NAMES),
      meta: { score: int(rng, 1, 999), owner: pick(rng, NAMES) },
    }));
    const idx = int(rng, 0, items.length - 1);
    const payload = { version: 2, batch: { items, note: pick(rng, NAMES) } };
    return capTask(
      "json-path",
      `The file data/payload.json in your workspace is a JSON document. Report the value at the path batch.items[${idx}].meta.score (zero-based index).`,
      String(items[idx]!.meta.score),
      { "data/payload.json": `${JSON.stringify(payload, null, 2)}\n` },
      ["files"],
    );
  },
  // 9. date-window: count events inside an inclusive date range.
  (rng) => {
    const lines: string[] = [];
    const startDay = int(rng, 3, 12);
    const endDay = startDay + int(rng, 5, 12);
    let inside = 0;
    const n = int(rng, 25, 45);
    for (let i = 0; i < n; i++) {
      const day = int(rng, 1, 28);
      const month = rng() < 0.8 ? 9 : 8;
      if (month === 9 && day >= startDay && day <= endDay) {
        inside += 1;
      }
      lines.push(
        `2026-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")} ${pick(rng, NAMES)}`,
      );
    }
    const pad = (d: number) => String(d).padStart(2, "0");
    return capTask(
      "date-window",
      `The file data/events.txt in your workspace has one event per line as "<YYYY-MM-DD> <name>". How many events have a date from 2026-09-${pad(startDay)} through 2026-09-${pad(endDay)} inclusive? Report the integer.`,
      String(inside),
      { "data/events.txt": `${shuffle(rng, lines).join("\n")}\n` },
      ["files", "exec"],
    );
  },
];

/** Total bytes of a task's files (0 when none). */
export function taskFileBytes(task: CorpusTask): number {
  return Object.values(task.files ?? {}).reduce((a, s) => a + Buffer.byteLength(s, "utf-8"), 0);
}
