export const browserCoreExamples = [
  "bitterbot browser status",
  "bitterbot browser start",
  "bitterbot browser stop",
  "bitterbot browser tabs",
  "bitterbot browser open https://example.com",
  "bitterbot browser focus abcd1234",
  "bitterbot browser close abcd1234",
  "bitterbot browser screenshot",
  "bitterbot browser screenshot --full-page",
  "bitterbot browser screenshot --ref 12",
  "bitterbot browser snapshot",
  "bitterbot browser snapshot --format aria --limit 200",
  "bitterbot browser snapshot --efficient",
  "bitterbot browser snapshot --labels",
];

export const browserActionExamples = [
  "bitterbot browser navigate https://example.com",
  "bitterbot browser resize 1280 720",
  "bitterbot browser click 12 --double",
  'bitterbot browser type 23 "hello" --submit',
  "bitterbot browser press Enter",
  "bitterbot browser hover 44",
  "bitterbot browser drag 10 11",
  "bitterbot browser select 9 OptionA OptionB",
  "bitterbot browser upload /tmp/bitterbot/uploads/file.pdf",
  'bitterbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "bitterbot browser dialog --accept",
  'bitterbot browser wait --text "Done"',
  "bitterbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "bitterbot browser console --level error",
  "bitterbot browser pdf",
];
