/**
 * Integration test: full management node startup flow.
 *
 * Simulates what the gateway does when starting a management-tier node:
 *   config → trust list → orchestrator identity (IPC) → ManagementKeyAuth
 *     → ManagementNodeService → signed operations (delegated to orchestrator)
 *
 * The orchestrator's libp2p Ed25519 keypair is the canonical management
 * identity. JS never holds the private key — signing flows through IPC.
 */

import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import type { OrchestratorBridge } from "../infra/orchestrator-bridge.js";
import {
  ManagementKeyAuth,
  ManagementKeyAuthError,
  loadGenesisTrustList,
} from "./management-key-auth.js";
import { ManagementNodeService } from "./management-node-service.js";
import { ensureMemoryIndexSchema, ensureColumn } from "./memory-schema.js";
import { PeerReputationManager } from "./peer-reputation.js";
import { SkillExecutionTracker } from "./skill-execution-tracker.js";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function generateKeypair() {
  const { privateKey, publicKey } = crypto.generateKeyPairSync("ed25519");
  const pkcs8Der = privateKey.export({ format: "der", type: "pkcs8" });
  const seed = Buffer.from(pkcs8Der.subarray(pkcs8Der.length - 32));
  const spkiDer = publicKey.export({ format: "der", type: "spki" });
  const rawPub = Buffer.from(spkiDer.subarray(12));
  return { seedBase64: seed.toString("base64"), pubkeyBase64: rawPub.toString("base64") };
}

function createTestDb(): DatabaseSync {
  const db = new DatabaseSync(":memory:");
  ensureMemoryIndexSchema({
    db,
    embeddingCacheTable: "embedding_cache",
    ftsTable: "chunks_fts",
    ftsEnabled: false,
  });
  ensureColumn(db, "chunks", "publish_visibility", "TEXT");
  ensureColumn(db, "chunks", "published_at", "INTEGER");
  return db;
}

interface MockTelemetryEvent {
  signal_type: string;
  data: unknown;
  author_peer_id: string;
  author_pubkey?: string;
  timestamp: number;
}

/**
 * Build a mock bridge whose `getIdentity` returns the given pubkey.
 * Represents the orchestrator's libp2p identity — the management-node
 * authority. `sendCommand` returns `{ ok: true }` by default.
 */
function createMockBridge(pubkeyBase64: string) {
  const commands: Array<{ cmd: string; args: unknown }> = [];
  const telemetryCbs: Array<(event: MockTelemetryEvent) => void> = [];
  return {
    commands,
    telemetryCbs,
    isConnected: () => true,
    getIdentity: async () => ({
      pubkey: pubkeyBase64,
      peerId: `12D3KooW${pubkeyBase64.slice(0, 8)}`,
      nodeTier: "management",
    }),
    sendCommand: async (cmd: string, args: unknown) => {
      commands.push({ cmd, args });
      return { ok: true };
    },
    onTelemetryReceived: (cb: (event: MockTelemetryEvent) => void) => {
      telemetryCbs.push(cb);
    },
  };
}

/**
 * Produce a signed envelope using Node crypto directly — simulates what the
 * Rust orchestrator would broadcast. Used to verify cross-node verification
 * logic in `verifyCommand`.
 */
function signEnvelopeDirect(
  command: string,
  payload: Record<string, unknown>,
  timestamp: number,
  seedBase64: string,
  pubkeyBase64: string,
) {
  const seed = Buffer.from(seedBase64, "base64");
  const pkcs8Prefix = Buffer.from("302e020100300506032b657004220420", "hex");
  const pkcs8Der = Buffer.concat([pkcs8Prefix, seed]);
  const privateKey = crypto.createPrivateKey({ key: pkcs8Der, format: "der", type: "pkcs8" });
  const canonical = JSON.stringify({ command, payload, timestamp });
  const sig = crypto.sign(null, Buffer.from(canonical), privateKey);
  return {
    command,
    payload,
    timestamp,
    pubkey: pubkeyBase64,
    signature: sig.toString("base64"),
  };
}

// ─── Integration Tests ───────────────────────────────────────────────────────

describe("Management Node Integration", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "mgmt-integ-"));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("full startup: config → trust list → IPC identity → auth → service → ban", async () => {
    // 1. Represent the orchestrator's libp2p keypair (generated by Rust at `keys/node.key`).
    const orchestratorKey = generateKeypair();

    // 2. Write trust list file (~/.bitterbot/genesis-trust.txt).
    const trustListPath = path.join(tmpDir, "genesis-trust.txt");
    fs.writeFileSync(
      trustListPath,
      ["# Genesis trust list for test network", orchestratorKey.pubkeyBase64, ""].join("\n"),
    );

    // 3. Load trust list.
    const trustList = loadGenesisTrustList(trustListPath);
    expect(trustList).toEqual([orchestratorKey.pubkeyBase64]);

    // 4. Auth queries the orchestrator for its identity, verifies against trust list.
    const bridge = createMockBridge(orchestratorKey.pubkeyBase64);
    const auth = await ManagementKeyAuth.init(trustList, bridge as unknown as OrchestratorBridge);
    expect(auth.publicKeyBase64).toBe(orchestratorKey.pubkeyBase64);

    // 5. Create management node service with auth.
    const db = createTestDb();
    const tracker = new SkillExecutionTracker(db);
    const peerRep = new PeerReputationManager(db, tracker, trustList);
    const service = new ManagementNodeService(
      db,
      bridge as unknown as OrchestratorBridge,
      peerRep,
      null,
      auth,
    );

    expect(service.isAuthorized).toBe(true);
    expect(service.publicKey).toBe(orchestratorKey.pubkeyBase64);

    // 6. Start (does not throw).
    service.start();

    // 7. Propagate a ban — TS forwards to orchestrator, which signs internally.
    const banResult = await service.propagateBan("malicious-peer-pubkey", "spam flood");
    expect(banResult).toBe(true);

    // 8. Bridge received the forwarded command.
    expect(bridge.commands.length).toBe(1);
    const banCmd = bridge.commands[0]!;
    expect(banCmd.cmd).toBe("propagate_ban");
    const args = banCmd.args as Record<string, unknown>;
    expect(args.peer_pubkey).toBe("malicious-peer-pubkey");
    expect(args.reason).toBe("spam flood");
    // TS no longer produces signature envelopes — the orchestrator does.
    expect(args.management_signature).toBeUndefined();
    expect(args.management_pubkey).toBeUndefined();

    // 9. Local reputation was updated.
    expect(peerRep.isBanned("malicious-peer-pubkey")).toBe(true);

    // 10. Management node is recognized in reputation system.
    expect(peerRep.isManagementNode(orchestratorKey.pubkeyBase64)).toBe(true);

    service.stop();
  });

  it("rejects startup when bridge is not connected", async () => {
    const orchestratorKey = generateKeypair();
    const trustList = [orchestratorKey.pubkeyBase64];

    const disconnectedBridge = {
      isConnected: () => false,
      getIdentity: async () => ({
        pubkey: orchestratorKey.pubkeyBase64,
        peerId: "peer-id",
        nodeTier: "management",
      }),
    };

    await expect(
      ManagementKeyAuth.init(trustList, disconnectedBridge as unknown as OrchestratorBridge),
    ).rejects.toMatchObject({
      name: "ManagementKeyAuthError",
      code: "BRIDGE_NOT_READY",
    });

    // Service without auth refuses to start
    const db = createTestDb();
    const bridge = createMockBridge(orchestratorKey.pubkeyBase64);
    const service = new ManagementNodeService(db, bridge as unknown as OrchestratorBridge);
    expect(() => service.start()).toThrow("cannot start without management-node authorization");
  });

  it("rejects when orchestrator pubkey is not in trust list", async () => {
    const orchestratorKey = generateKeypair();
    const otherKey = generateKeypair();

    // Trust list only has the "other" key — orchestrator's own pubkey is not trusted.
    const trustList = [otherKey.pubkeyBase64];
    const bridge = createMockBridge(orchestratorKey.pubkeyBase64);

    await expect(
      ManagementKeyAuth.init(trustList, bridge as unknown as OrchestratorBridge),
    ).rejects.toMatchObject({
      name: "ManagementKeyAuthError",
      code: "KEY_NOT_IN_TRUST_LIST",
    });
  });

  it("multi-node trust: two management nodes verify each other's ban broadcasts", async () => {
    const node1 = generateKeypair();
    const node2 = generateKeypair();
    const trustList = [node1.pubkeyBase64, node2.pubkeyBase64];

    // Node 1's auth
    const bridge1 = createMockBridge(node1.pubkeyBase64);
    const auth1 = await ManagementKeyAuth.init(trustList, bridge1 as unknown as OrchestratorBridge);
    expect(auth1.publicKeyBase64).toBe(node1.pubkeyBase64);

    // Node 2's auth
    const bridge2 = createMockBridge(node2.pubkeyBase64);
    const auth2 = await ManagementKeyAuth.init(trustList, bridge2 as unknown as OrchestratorBridge);
    expect(auth2.publicKeyBase64).toBe(node2.pubkeyBase64);

    // Node 1 broadcasts a ban — simulate what the orchestrator would sign and emit.
    const timestamp = Date.now();
    const broadcast = signEnvelopeDirect(
      "propagate_ban",
      { peer_pubkey: "evil-peer", reason: "malicious behavior" },
      timestamp,
      node1.seedBase64,
      node1.pubkeyBase64,
    );

    // Node 2 verifies the broadcast against the shared trust list.
    expect(ManagementKeyAuth.verifyCommand(broadcast, trustList)).toBe(true);

    // Forged signature is rejected.
    const forged = { ...broadcast, signature: "AAAA" + broadcast.signature.slice(4) };
    expect(ManagementKeyAuth.verifyCommand(forged, trustList)).toBe(false);
  });

  it("handleBanReceived verifies management source via reputation", async () => {
    const mgmtKey = generateKeypair();
    const edgeKey = generateKeypair();
    const trustList = [mgmtKey.pubkeyBase64];

    const db = createTestDb();
    const bridge = createMockBridge(mgmtKey.pubkeyBase64);
    const tracker = new SkillExecutionTracker(db);
    const rep = new PeerReputationManager(db, tracker, trustList);
    const auth = await ManagementKeyAuth.init(trustList, bridge as unknown as OrchestratorBridge);
    const service = new ManagementNodeService(
      db,
      bridge as unknown as OrchestratorBridge,
      rep,
      null,
      auth,
    );
    service.start();

    const telemetryCb = bridge.telemetryCbs[0]!;

    // Valid ban from management node
    telemetryCb({
      signal_type: "management_ban",
      data: { peer_pubkey: "target-peer", reason: "bad actor" },
      author_peer_id: "mgmt-peer-123",
      author_pubkey: mgmtKey.pubkeyBase64,
      timestamp: Date.now(),
    });
    expect(rep.isBanned("target-peer")).toBe(true);

    // Invalid ban from edge node (not in trust list) — should be rejected
    telemetryCb({
      signal_type: "management_ban",
      data: { peer_pubkey: "innocent-peer", reason: "attempted ban" },
      author_peer_id: "edge-peer-456",
      author_pubkey: edgeKey.pubkeyBase64,
      timestamp: Date.now(),
    });
    expect(rep.isBanned("innocent-peer")).toBe(false);

    service.stop();
  });

  it("loadGenesisTrustList tolerates missing files and mixed sources", () => {
    const missing = loadGenesisTrustList("/nonexistent/path.txt");
    expect(missing).toEqual([]);

    const inline = loadGenesisTrustList(undefined, ["a", "b"]);
    expect(inline).toEqual(["a", "b"]);

    const filePath = path.join(tmpDir, "trust.txt");
    fs.writeFileSync(filePath, "# comment\nkey-from-file\n");
    const merged = loadGenesisTrustList(filePath, ["inline-key", "key-from-file"]);
    // Dedup preserves first occurrence order
    expect(merged).toEqual(["inline-key", "key-from-file"]);
  });

  it("ManagementKeyAuthError surfaces structured codes", () => {
    const err = new ManagementKeyAuthError("test message", "KEY_NOT_IN_TRUST_LIST");
    expect(err.name).toBe("ManagementKeyAuthError");
    expect(err.code).toBe("KEY_NOT_IN_TRUST_LIST");
    expect(err.message).toBe("test message");
  });
});
