import { DatabaseSync } from "node:sqlite";
import { describe, it, expect } from "vitest";
import {
  buildDigest,
  msUntilLocalTime,
  renderMarkdown,
  type DigestReport,
} from "./skill-pipeline-digest.js";

function createTestDb(): DatabaseSync {
  const db = new DatabaseSync(":memory:");
  db.exec(`
    CREATE TABLE IF NOT EXISTS dream_cycles (
      cycle_id TEXT PRIMARY KEY,
      started_at INTEGER NOT NULL,
      completed_at INTEGER,
      duration_ms INTEGER,
      state TEXT,
      insights_generated INTEGER DEFAULT 0,
      error TEXT
    );
    CREATE TABLE IF NOT EXISTS dream_outcomes (
      cycle_id TEXT PRIMARY KEY,
      dqs REAL NOT NULL,
      crystal_yield REAL DEFAULT 0,
      modes_run TEXT,
      timestamp INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS curiosity_targets (
      id TEXT PRIMARY KEY,
      type TEXT NOT NULL,
      description TEXT NOT NULL,
      priority REAL,
      metadata TEXT DEFAULT '{}',
      created_at INTEGER NOT NULL,
      resolved_at INTEGER,
      expires_at INTEGER
    );
    CREATE TABLE IF NOT EXISTS marketplace_listings (
      skill_crystal_id TEXT PRIMARY KEY,
      name TEXT,
      price_usdc REAL,
      listable INTEGER DEFAULT 0,
      listed_at INTEGER,
      updated_at INTEGER
    );
    CREATE TABLE IF NOT EXISTS marketplace_purchases (
      id TEXT PRIMARY KEY,
      skill_crystal_id TEXT NOT NULL,
      buyer_peer_id TEXT,
      amount_usdc REAL NOT NULL,
      purchased_at INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS skill_executions (
      id TEXT PRIMARY KEY,
      skill_crystal_id TEXT NOT NULL,
      started_at INTEGER NOT NULL,
      completed_at INTEGER,
      success INTEGER,
      reward_score REAL,
      error_type TEXT
    );
    CREATE TABLE IF NOT EXISTS chunks (
      id TEXT PRIMARY KEY,
      skill_category TEXT,
      tags TEXT,
      created_at INTEGER
    );
  `);
  return db;
}

const now = Date.now();
const HOUR = 60 * 60 * 1000;

describe("skill-pipeline-digest", () => {
  describe("buildDigest", () => {
    it("returns zero-activity report for an empty DB", () => {
      const db = createTestDb();
      const r = buildDigest(db, { sinceMs: now - 24 * HOUR, untilMs: now });
      expect(r.dreams.cyclesCompleted).toBe(0);
      expect(r.skills.autoGeneratedCount).toBe(0);
      expect(r.curiosity.newTargets).toBe(0);
      expect(r.marketplace.purchases).toBe(0);
      expect(r.executions.total).toBe(0);
      expect(r.errors.dreamErrors).toHaveLength(0);
    });

    it("aggregates dream cycles in window", () => {
      const db = createTestDb();
      db.prepare(
        `INSERT INTO dream_cycles (cycle_id, started_at, completed_at, duration_ms, state, insights_generated, error) VALUES (?, ?, ?, ?, ?, ?, ?)`,
      ).run("c1", now - 2 * HOUR, now - 2 * HOUR + 5000, 5000, "COMPLETE", 3, null);
      db.prepare(
        `INSERT INTO dream_cycles (cycle_id, started_at, completed_at, duration_ms, state, insights_generated, error) VALUES (?, ?, ?, ?, ?, ?, ?)`,
      ).run("c2", now - 1 * HOUR, now - 1 * HOUR + 3000, 3000, "COMPLETE", 2, null);
      db.prepare(
        `INSERT INTO dream_cycles (cycle_id, started_at, completed_at, duration_ms, state, insights_generated, error) VALUES (?, ?, ?, ?, ?, ?, ?)`,
      ).run("c3", now - 30 * HOUR, now - 30 * HOUR + 2000, 2000, "COMPLETE", 1, null);

      const r = buildDigest(db, { sinceMs: now - 24 * HOUR, untilMs: now });
      expect(r.dreams.cyclesCompleted).toBe(2);
      expect(r.dreams.totalInsights).toBe(5);
      expect(r.dreams.cyclesWithErrors).toBe(0);
      expect(r.dreams.avgDurationMs).toBe(4000);
    });

    it("captures dream errors", () => {
      const db = createTestDb();
      db.prepare(
        `INSERT INTO dream_cycles (cycle_id, started_at, completed_at, state, insights_generated, error) VALUES (?, ?, ?, ?, ?, ?)`,
      ).run("bad", now - 3 * HOUR, now - 3 * HOUR + 100, "FAILED", 0, "OOM");
      const r = buildDigest(db, { sinceMs: now - 24 * HOUR, untilMs: now });
      expect(r.dreams.cyclesWithErrors).toBe(1);
      expect(r.errors.dreamErrors).toHaveLength(1);
      expect(r.errors.dreamErrors[0]?.error).toBe("OOM");
    });

    it("counts auto-generated skills from chunk tags", () => {
      const db = createTestDb();
      db.prepare(
        `INSERT INTO chunks (id, skill_category, tags, created_at) VALUES (?, ?, ?, ?)`,
      ).run(
        "react-hooks",
        "docs",
        JSON.stringify(["external-generated", "transport:native"]),
        now - 2 * HOUR,
      );
      db.prepare(
        `INSERT INTO chunks (id, skill_category, tags, created_at) VALUES (?, ?, ?, ?)`,
      ).run(
        "nextjs-routing",
        "docs",
        JSON.stringify(["external-generated", "transport:cli"]),
        now - 5 * HOUR,
      );
      db.prepare(
        `INSERT INTO chunks (id, skill_category, tags, created_at) VALUES (?, ?, ?, ?)`,
      ).run("manual-skill", "coding", JSON.stringify(["hand-written"]), now - 1 * HOUR);

      const r = buildDigest(db, { sinceMs: now - 24 * HOUR, untilMs: now });
      expect(r.skills.autoGeneratedCount).toBe(2);
      expect(r.skills.byTransport).toEqual({ native: 1, cli: 1 });
      expect(r.skills.byCategory).toEqual({ docs: 2 });
    });

    it("aggregates marketplace activity with top categories", () => {
      const db = createTestDb();
      db.prepare(
        `INSERT INTO chunks (id, skill_category, tags, created_at) VALUES (?, ?, ?, ?)`,
      ).run("weather-api", "weather", "[]", now - 10 * HOUR);
      db.prepare(
        `INSERT INTO chunks (id, skill_category, tags, created_at) VALUES (?, ?, ?, ?)`,
      ).run("weather-api-v2", "weather", "[]", now - 10 * HOUR);

      db.prepare(
        `INSERT INTO marketplace_purchases (id, skill_crystal_id, buyer_peer_id, amount_usdc, purchased_at) VALUES (?, ?, ?, ?, ?)`,
      ).run("p1", "weather-api", "peer1", 2.5, now - 3 * HOUR);
      db.prepare(
        `INSERT INTO marketplace_purchases (id, skill_crystal_id, buyer_peer_id, amount_usdc, purchased_at) VALUES (?, ?, ?, ?, ?)`,
      ).run("p2", "weather-api-v2", "peer2", 1.0, now - 1 * HOUR);

      const r = buildDigest(db, { sinceMs: now - 24 * HOUR, untilMs: now });
      expect(r.marketplace.purchases).toBe(2);
      expect(r.marketplace.revenueUsdc).toBe(3.5);
      expect(r.marketplace.topCategories[0]?.category).toBe("weather");
      expect(r.marketplace.topCategories[0]?.purchases).toBe(2);
    });

    it("computes success rate from skill executions", () => {
      const db = createTestDb();
      db.prepare(
        `INSERT INTO skill_executions (id, skill_crystal_id, started_at, completed_at, success, reward_score, error_type) VALUES (?, ?, ?, ?, ?, ?, ?)`,
      ).run("e1", "s1", now - 3 * HOUR, now - 3 * HOUR + 500, 1, 0.8, null);
      db.prepare(
        `INSERT INTO skill_executions (id, skill_crystal_id, started_at, completed_at, success, reward_score, error_type) VALUES (?, ?, ?, ?, ?, ?, ?)`,
      ).run("e2", "s1", now - 2 * HOUR, now - 2 * HOUR + 600, 0, 0.0, "timeout");
      db.prepare(
        `INSERT INTO skill_executions (id, skill_crystal_id, started_at, completed_at, success, reward_score, error_type) VALUES (?, ?, ?, ?, ?, ?, ?)`,
      ).run("e3", "s2", now - 1 * HOUR, now - 1 * HOUR + 400, 1, 0.9, null);

      const r = buildDigest(db, { sinceMs: now - 24 * HOUR, untilMs: now });
      expect(r.executions.total).toBe(3);
      expect(r.executions.successful).toBe(2);
      expect(r.executions.failed).toBe(1);
      expect(r.executions.successRate).toBeCloseTo(2 / 3, 3);
      expect(r.errors.executionErrors[0]).toEqual({ errorType: "timeout", count: 1 });
    });

    it("excludes events outside the window", () => {
      const db = createTestDb();
      db.prepare(
        `INSERT INTO dream_cycles (cycle_id, started_at, completed_at, state, insights_generated) VALUES (?, ?, ?, ?, ?)`,
      ).run("old", now - 48 * HOUR, now - 48 * HOUR + 1000, "COMPLETE", 5);
      db.prepare(
        `INSERT INTO dream_cycles (cycle_id, started_at, completed_at, state, insights_generated) VALUES (?, ?, ?, ?, ?)`,
      ).run("recent", now - 2 * HOUR, now - 2 * HOUR + 1000, "COMPLETE", 2);

      const r = buildDigest(db, { sinceMs: now - 24 * HOUR, untilMs: now });
      expect(r.dreams.cyclesCompleted).toBe(1);
      expect(r.dreams.totalInsights).toBe(2);
    });
  });

  describe("renderMarkdown", () => {
    it("renders a quiet-period notice when nothing happened", () => {
      const report: DigestReport = {
        windowStart: now - 24 * HOUR,
        windowEnd: now,
        windowHours: 24,
        generatedAt: now,
        dreams: {
          cyclesCompleted: 0,
          cyclesWithErrors: 0,
          totalInsights: 0,
          avgDurationMs: null,
          latestDqs: null,
          modesUsed: {},
        },
        skills: { autoGeneratedCount: 0, autoGeneratedNames: [], byTransport: {}, byCategory: {} },
        curiosity: { newTargets: 0, byType: {}, resolved: 0 },
        marketplace: {
          newListings: 0,
          totalListable: 0,
          purchases: 0,
          revenueUsdc: 0,
          topCategories: [],
        },
        executions: { total: 0, successful: 0, failed: 0, successRate: null, avgRewardScore: null },
        errors: { executionErrors: [], dreamErrors: [] },
      };
      const md = renderMarkdown(report);
      expect(md).toContain("# Skill Pipeline Digest");
      expect(md).toContain("No autonomous activity in this window");
    });

    it("renders sections that have data", () => {
      const db = createTestDb();
      db.prepare(
        `INSERT INTO dream_cycles (cycle_id, started_at, completed_at, state, insights_generated) VALUES (?, ?, ?, ?, ?)`,
      ).run("c1", now - 2 * HOUR, now - 2 * HOUR + 5000, "COMPLETE", 3);
      db.prepare(
        `INSERT INTO skill_executions (id, skill_crystal_id, started_at, completed_at, success, reward_score) VALUES (?, ?, ?, ?, ?, ?)`,
      ).run("e1", "s1", now - 1 * HOUR, now - 1 * HOUR + 500, 1, 0.7);

      const report = buildDigest(db, { sinceMs: now - 24 * HOUR, untilMs: now });
      const md = renderMarkdown(report);
      expect(md).toContain("## Dream cycles");
      expect(md).toContain("1 completed");
      expect(md).toContain("3 insights generated");
      expect(md).toContain("## Skill executions");
      expect(md).toContain("1 total (1 successful");
    });
  });

  describe("msUntilLocalTime", () => {
    it("returns a positive value for future times today", () => {
      const now = new Date();
      // Pick a time that's guaranteed in the future this year.
      const futureHour = (now.getHours() + 2) % 24;
      const hhmm = `${String(futureHour).padStart(2, "0")}:00`;
      const ms = msUntilLocalTime(hhmm);
      expect(ms).toBeGreaterThan(0);
      expect(ms).toBeLessThan(25 * 60 * 60 * 1000);
    });

    it("schedules for tomorrow when the target already passed today", () => {
      const now = new Date();
      const pastHour = Math.max(0, now.getHours() - 2);
      const hhmm = `${String(pastHour).padStart(2, "0")}:00`;
      const ms = msUntilLocalTime(hhmm);
      expect(ms).toBeGreaterThan(0);
      // Must be tomorrow (so >20h away)
      expect(ms).toBeGreaterThan(20 * 60 * 60 * 1000);
      expect(ms).toBeLessThan(25 * 60 * 60 * 1000);
    });

    it("rejects malformed time strings", () => {
      expect(() => msUntilLocalTime("25:00")).toThrow();
      expect(() => msUntilLocalTime("nope")).toThrow();
      expect(() => msUntilLocalTime("9:00")).toThrow(); // Must be HH:MM
    });
  });
});
