/**
 * Skill Pipeline Daily Digest
 *
 * PLAN-11 Gap 6: observability. Composes a human-readable summary of autonomous
 * actions the skill pipeline has taken over a lookback window (default 24h)
 * and delivers it through configurable channels.
 *
 * The content already exists in the DB across several tables — this module
 * is a reporting layer, not new accounting. It is intentionally read-only:
 * building a digest must never mutate memory state.
 *
 * Tables queried (all fully schema-documented in src/memory/dream-schema.ts,
 * src/memory/curiosity-schema.ts, src/memory/marketplace-economics.ts,
 * src/memory/migrations.ts):
 *   - dream_cycles         → count, errors, duration, insights
 *   - dream_outcomes       → DQS, modes run
 *   - curiosity_targets    → new targets by source (market_demand, knowledge_gap, frequency)
 *   - marketplace_listings → listable counts, price changes
 *   - marketplace_purchases→ sales volume and revenue
 *   - skill_executions     → execution counts, success rate, error types
 *   - chunks               → new auto-generated skills (via tags JSON)
 */

import type { DatabaseSync } from "node:sqlite";
import fs from "node:fs";
import path from "node:path";
import { createSubsystemLogger } from "../logging/subsystem.js";

const log = createSubsystemLogger("skill-pipeline-digest");

// ── Types ──

export type DigestReport = {
  windowStart: number;
  windowEnd: number;
  windowHours: number;
  generatedAt: number;
  dreams: DreamSection;
  skills: SkillsSection;
  curiosity: CuriositySection;
  marketplace: MarketplaceSection;
  executions: ExecutionsSection;
  errors: ErrorsSection;
};

export type DreamSection = {
  cyclesCompleted: number;
  cyclesWithErrors: number;
  totalInsights: number;
  avgDurationMs: number | null;
  latestDqs: number | null;
  modesUsed: Record<string, number>;
};

export type SkillsSection = {
  autoGeneratedCount: number;
  autoGeneratedNames: string[];
  byTransport: Record<string, number>;
  byCategory: Record<string, number>;
};

export type CuriositySection = {
  newTargets: number;
  byType: Record<string, number>;
  resolved: number;
};

export type MarketplaceSection = {
  newListings: number;
  totalListable: number;
  purchases: number;
  revenueUsdc: number;
  topCategories: Array<{ category: string; purchases: number; revenueUsdc: number }>;
};

export type ExecutionsSection = {
  total: number;
  successful: number;
  failed: number;
  successRate: number | null;
  avgRewardScore: number | null;
};

export type ErrorsSection = {
  executionErrors: Array<{ errorType: string; count: number }>;
  dreamErrors: Array<{ cycleId: string; error: string; at: number }>;
};

// ── Build ──

export type BuildDigestOptions = {
  /** Window start (unix ms). Default: now - 24h. */
  sinceMs?: number;
  /** Window end (unix ms). Default: now. */
  untilMs?: number;
};

export function buildDigest(db: DatabaseSync, opts: BuildDigestOptions = {}): DigestReport {
  const now = Date.now();
  const windowEnd = opts.untilMs ?? now;
  const windowStart = opts.sinceMs ?? windowEnd - 24 * 60 * 60 * 1000;
  const windowHours = (windowEnd - windowStart) / (60 * 60 * 1000);

  return {
    windowStart,
    windowEnd,
    windowHours,
    generatedAt: now,
    dreams: buildDreamSection(db, windowStart, windowEnd),
    skills: buildSkillsSection(db, windowStart, windowEnd),
    curiosity: buildCuriositySection(db, windowStart, windowEnd),
    marketplace: buildMarketplaceSection(db, windowStart, windowEnd),
    executions: buildExecutionsSection(db, windowStart, windowEnd),
    errors: buildErrorsSection(db, windowStart, windowEnd),
  };
}

function buildDreamSection(db: DatabaseSync, start: number, end: number): DreamSection {
  const cyclesRow = db
    .prepare(
      `SELECT COUNT(*) AS total,
              SUM(CASE WHEN error IS NOT NULL AND error <> '' THEN 1 ELSE 0 END) AS with_errors,
              COALESCE(SUM(insights_generated), 0) AS total_insights,
              AVG(duration_ms) AS avg_duration
       FROM dream_cycles
       WHERE completed_at IS NOT NULL AND started_at >= ? AND started_at < ?`,
    )
    .get(start, end) as
    | { total: number; with_errors: number; total_insights: number; avg_duration: number | null }
    | undefined;

  const latest = db
    .prepare(
      `SELECT dqs FROM dream_outcomes
       WHERE timestamp >= ? AND timestamp < ?
       ORDER BY timestamp DESC LIMIT 1`,
    )
    .get(start, end) as { dqs: number } | undefined;

  const modesUsed: Record<string, number> = {};
  try {
    const outcomes = db
      .prepare(
        `SELECT modes_run FROM dream_outcomes
         WHERE timestamp >= ? AND timestamp < ? AND modes_run IS NOT NULL`,
      )
      .all(start, end) as Array<{ modes_run: string }>;
    for (const row of outcomes) {
      try {
        const modes = JSON.parse(row.modes_run);
        if (Array.isArray(modes)) {
          for (const mode of modes) {
            if (typeof mode === "string") {
              modesUsed[mode] = (modesUsed[mode] ?? 0) + 1;
            }
          }
        }
      } catch {
        // malformed row — skip
      }
    }
  } catch {
    // modes_run column may not exist in older installs
  }

  return {
    cyclesCompleted: cyclesRow?.total ?? 0,
    cyclesWithErrors: cyclesRow?.with_errors ?? 0,
    totalInsights: cyclesRow?.total_insights ?? 0,
    avgDurationMs: cyclesRow?.avg_duration ?? null,
    latestDqs: latest?.dqs ?? null,
    modesUsed,
  };
}

function buildSkillsSection(db: DatabaseSync, start: number, end: number): SkillsSection {
  // Auto-generated skills live in chunks with tag "external-generated".
  // The adapter also embeds `transport:<kind>` as a tag.
  let rows: Array<{ id: string; skill_category: string | null; tags: string | null }> = [];
  try {
    rows = db
      .prepare(
        `SELECT id, skill_category, tags FROM chunks
         WHERE created_at >= ? AND created_at < ?
           AND COALESCE(tags, '[]') LIKE '%external-generated%'`,
      )
      .all(start, end) as typeof rows;
  } catch {
    // chunks table or tags column may not exist
  }

  const names: string[] = [];
  const byTransport: Record<string, number> = {};
  const byCategory: Record<string, number> = {};

  for (const row of rows) {
    names.push(row.id);
    const category = row.skill_category ?? "uncategorized";
    byCategory[category] = (byCategory[category] ?? 0) + 1;

    let transport = "unknown";
    try {
      const tags = JSON.parse(row.tags ?? "[]") as string[];
      const t = tags.find((x) => typeof x === "string" && x.startsWith("transport:"));
      if (t) {
        transport = t.slice("transport:".length);
      }
    } catch {
      // tag parse failed
    }
    byTransport[transport] = (byTransport[transport] ?? 0) + 1;
  }

  return {
    autoGeneratedCount: rows.length,
    autoGeneratedNames: names.slice(0, 20),
    byTransport,
    byCategory,
  };
}

function buildCuriositySection(db: DatabaseSync, start: number, end: number): CuriositySection {
  let byType: Array<{ type: string; count: number }> = [];
  try {
    byType = db
      .prepare(
        `SELECT type, COUNT(*) as count FROM curiosity_targets
         WHERE created_at >= ? AND created_at < ?
         GROUP BY type`,
      )
      .all(start, end) as typeof byType;
  } catch {
    // table absent
  }

  const byTypeMap: Record<string, number> = {};
  let newTargets = 0;
  for (const row of byType) {
    byTypeMap[row.type] = row.count;
    newTargets += row.count;
  }

  let resolved = 0;
  try {
    const resolvedRow = db
      .prepare(
        `SELECT COUNT(*) as count FROM curiosity_targets
         WHERE resolved_at IS NOT NULL AND resolved_at >= ? AND resolved_at < ?`,
      )
      .get(start, end) as { count: number } | undefined;
    resolved = resolvedRow?.count ?? 0;
  } catch {
    // table absent
  }

  return { newTargets, byType: byTypeMap, resolved };
}

function buildMarketplaceSection(db: DatabaseSync, start: number, end: number): MarketplaceSection {
  let newListings = 0;
  let totalListable = 0;
  try {
    const listingsNew = db
      .prepare(
        `SELECT COUNT(*) as count FROM marketplace_listings
         WHERE listed_at IS NOT NULL AND listed_at >= ? AND listed_at < ?`,
      )
      .get(start, end) as { count: number } | undefined;
    newListings = listingsNew?.count ?? 0;

    const listable = db
      .prepare(`SELECT COUNT(*) as count FROM marketplace_listings WHERE listable = 1`)
      .get() as { count: number } | undefined;
    totalListable = listable?.count ?? 0;
  } catch {
    // marketplace tables may not exist in all installs
  }

  let purchases = 0;
  let revenueUsdc = 0;
  let topCategories: Array<{ category: string; purchases: number; revenueUsdc: number }> = [];
  try {
    const purchasesRow = db
      .prepare(
        `SELECT COUNT(*) as count, COALESCE(SUM(amount_usdc), 0) as revenue
         FROM marketplace_purchases
         WHERE purchased_at >= ? AND purchased_at < ?`,
      )
      .get(start, end) as { count: number; revenue: number } | undefined;
    purchases = purchasesRow?.count ?? 0;
    revenueUsdc = purchasesRow?.revenue ?? 0;

    // Top categories by purchase count in window.
    topCategories = db
      .prepare(
        `SELECT COALESCE(c.skill_category, 'uncategorized') as category,
                COUNT(*) as purchases,
                COALESCE(SUM(mp.amount_usdc), 0) as revenueUsdc
         FROM marketplace_purchases mp
         JOIN chunks c ON c.id = mp.skill_crystal_id
         WHERE mp.purchased_at >= ? AND mp.purchased_at < ?
         GROUP BY category
         ORDER BY purchases DESC, revenueUsdc DESC
         LIMIT 5`,
      )
      .all(start, end) as typeof topCategories;
  } catch {
    // marketplace tables may not exist
  }

  return { newListings, totalListable, purchases, revenueUsdc, topCategories };
}

function buildExecutionsSection(db: DatabaseSync, start: number, end: number): ExecutionsSection {
  let row: { total: number; successful: number; avg_reward: number | null } | undefined;
  try {
    row = db
      .prepare(
        `SELECT COUNT(*) as total,
                SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as successful,
                AVG(reward_score) as avg_reward
         FROM skill_executions
         WHERE completed_at IS NOT NULL AND started_at >= ? AND started_at < ?`,
      )
      .get(start, end) as typeof row;
  } catch {
    // table absent
  }

  const total = row?.total ?? 0;
  const successful = row?.successful ?? 0;
  return {
    total,
    successful,
    failed: total - successful,
    successRate: total > 0 ? successful / total : null,
    avgRewardScore: row?.avg_reward ?? null,
  };
}

function buildErrorsSection(db: DatabaseSync, start: number, end: number): ErrorsSection {
  let executionErrors: Array<{ errorType: string; count: number }> = [];
  try {
    executionErrors = db
      .prepare(
        `SELECT error_type as errorType, COUNT(*) as count FROM skill_executions
         WHERE completed_at IS NOT NULL
           AND started_at >= ? AND started_at < ?
           AND success = 0 AND error_type IS NOT NULL
         GROUP BY error_type
         ORDER BY count DESC
         LIMIT 10`,
      )
      .all(start, end) as typeof executionErrors;
  } catch {
    // table absent
  }

  let dreamErrors: Array<{ cycleId: string; error: string; at: number }> = [];
  try {
    dreamErrors = db
      .prepare(
        `SELECT cycle_id as cycleId, error, started_at as at FROM dream_cycles
         WHERE error IS NOT NULL AND error <> '' AND started_at >= ? AND started_at < ?
         ORDER BY started_at DESC
         LIMIT 5`,
      )
      .all(start, end) as typeof dreamErrors;
  } catch {
    // table absent
  }

  return { executionErrors, dreamErrors };
}

// ── Render ──

export function renderMarkdown(report: DigestReport): string {
  const lines: string[] = [];
  const startIso = new Date(report.windowStart).toISOString();
  const endIso = new Date(report.windowEnd).toISOString();

  lines.push(`# Skill Pipeline Digest`);
  lines.push("");
  lines.push(`**Window:** ${startIso} → ${endIso} (${report.windowHours.toFixed(1)}h)`);
  lines.push(`**Generated:** ${new Date(report.generatedAt).toISOString()}`);
  lines.push("");

  // Dreams
  if (report.dreams.cyclesCompleted > 0 || report.dreams.cyclesWithErrors > 0) {
    lines.push("## Dream cycles");
    lines.push("");
    lines.push(
      `- ${report.dreams.cyclesCompleted} completed${
        report.dreams.cyclesWithErrors > 0 ? ` (${report.dreams.cyclesWithErrors} with errors)` : ""
      }`,
    );
    lines.push(`- ${report.dreams.totalInsights} insights generated`);
    if (report.dreams.avgDurationMs != null) {
      lines.push(`- Avg duration: ${(report.dreams.avgDurationMs / 1000).toFixed(1)}s`);
    }
    if (report.dreams.latestDqs != null) {
      lines.push(`- Latest DQS: ${report.dreams.latestDqs.toFixed(3)}`);
    }
    const modes = Object.entries(report.dreams.modesUsed);
    if (modes.length > 0) {
      modes.sort((a, b) => b[1] - a[1]);
      lines.push(`- Modes used: ${modes.map(([m, n]) => `${m}×${n}`).join(", ")}`);
    }
    lines.push("");
  }

  // Skills
  if (report.skills.autoGeneratedCount > 0) {
    lines.push("## Skills learned");
    lines.push("");
    lines.push(`- ${report.skills.autoGeneratedCount} auto-generated skill(s)`);
    const transports = Object.entries(report.skills.byTransport);
    if (transports.length > 0) {
      lines.push(`- By transport: ${transports.map(([t, n]) => `${t}×${n}`).join(", ")}`);
    }
    const categories = Object.entries(report.skills.byCategory);
    if (categories.length > 0) {
      categories.sort((a, b) => b[1] - a[1]);
      lines.push(`- By category: ${categories.map(([c, n]) => `${c}×${n}`).join(", ")}`);
    }
    if (report.skills.autoGeneratedNames.length > 0) {
      lines.push(`- Examples: ${report.skills.autoGeneratedNames.slice(0, 5).join(", ")}`);
    }
    lines.push("");
  }

  // Curiosity
  if (report.curiosity.newTargets > 0 || report.curiosity.resolved > 0) {
    lines.push("## Curiosity signals");
    lines.push("");
    if (report.curiosity.newTargets > 0) {
      const types = Object.entries(report.curiosity.byType);
      lines.push(
        `- ${report.curiosity.newTargets} new target(s): ${types.map(([t, n]) => `${t}×${n}`).join(", ")}`,
      );
    }
    if (report.curiosity.resolved > 0) {
      lines.push(`- ${report.curiosity.resolved} target(s) resolved`);
    }
    lines.push("");
  }

  // Marketplace
  if (
    report.marketplace.newListings > 0 ||
    report.marketplace.purchases > 0 ||
    report.marketplace.totalListable > 0
  ) {
    lines.push("## Marketplace");
    lines.push("");
    if (report.marketplace.totalListable > 0) {
      lines.push(`- ${report.marketplace.totalListable} skill(s) currently listable`);
    }
    if (report.marketplace.newListings > 0) {
      lines.push(`- ${report.marketplace.newListings} new listing(s) in window`);
    }
    if (report.marketplace.purchases > 0) {
      lines.push(
        `- ${report.marketplace.purchases} purchase(s) — $${report.marketplace.revenueUsdc.toFixed(2)} USDC`,
      );
    }
    if (report.marketplace.topCategories.length > 0) {
      lines.push(`- Top categories:`);
      for (const c of report.marketplace.topCategories) {
        lines.push(
          `  - ${c.category}: ${c.purchases} purchase(s), $${c.revenueUsdc.toFixed(2)} USDC`,
        );
      }
    }
    lines.push("");
  }

  // Executions
  if (report.executions.total > 0) {
    lines.push("## Skill executions");
    lines.push("");
    lines.push(
      `- ${report.executions.total} total (${report.executions.successful} successful, ${report.executions.failed} failed)`,
    );
    if (report.executions.successRate != null) {
      lines.push(`- Success rate: ${(report.executions.successRate * 100).toFixed(1)}%`);
    }
    if (report.executions.avgRewardScore != null) {
      lines.push(`- Avg reward score: ${report.executions.avgRewardScore.toFixed(2)}`);
    }
    lines.push("");
  }

  // Errors
  if (report.errors.executionErrors.length > 0 || report.errors.dreamErrors.length > 0) {
    lines.push("## Errors / degraded paths");
    lines.push("");
    if (report.errors.executionErrors.length > 0) {
      lines.push(`- Execution error types:`);
      for (const e of report.errors.executionErrors) {
        lines.push(`  - ${e.errorType}: ${e.count}`);
      }
    }
    if (report.errors.dreamErrors.length > 0) {
      lines.push(`- Dream cycle errors:`);
      for (const e of report.errors.dreamErrors) {
        lines.push(`  - ${new Date(e.at).toISOString()} (${e.cycleId}): ${e.error}`);
      }
    }
    lines.push("");
  }

  // Quiet periods
  const hasContent =
    report.dreams.cyclesCompleted > 0 ||
    report.skills.autoGeneratedCount > 0 ||
    report.curiosity.newTargets > 0 ||
    report.curiosity.resolved > 0 ||
    report.marketplace.purchases > 0 ||
    report.marketplace.newListings > 0 ||
    report.executions.total > 0 ||
    report.errors.executionErrors.length > 0 ||
    report.errors.dreamErrors.length > 0;
  if (!hasContent) {
    lines.push("_No autonomous activity in this window._");
    lines.push("");
  }

  return lines.join("\n");
}

// ── Scheduling helpers ──

/**
 * Milliseconds from now until the next occurrence of a local-clock HH:MM time.
 * If the time has already passed today, schedules for tomorrow.
 */
export function msUntilLocalTime(hhmm: string): number {
  const match = hhmm.match(/^([01]\d|2[0-3]):([0-5]\d)$/);
  if (!match) {
    throw new Error(`Invalid time format: ${hhmm} (expected HH:MM)`);
  }
  const hour = Number.parseInt(match[1], 10);
  const minute = Number.parseInt(match[2], 10);
  const now = new Date();
  const target = new Date(now);
  target.setHours(hour, minute, 0, 0);
  if (target.getTime() <= now.getTime()) {
    target.setDate(target.getDate() + 1);
  }
  return target.getTime() - now.getTime();
}

// ── Delivery ──

export type DigestChannel =
  | { kind: "file"; dir: string }
  | { kind: "log" }
  | { kind: "message"; send: (markdown: string) => Promise<void> };

export async function deliverDigest(
  report: DigestReport,
  channels: DigestChannel[],
): Promise<void> {
  const markdown = renderMarkdown(report);
  for (const channel of channels) {
    try {
      if (channel.kind === "file") {
        const date = new Date(report.generatedAt);
        const y = date.getUTCFullYear();
        const m = String(date.getUTCMonth() + 1).padStart(2, "0");
        const d = String(date.getUTCDate()).padStart(2, "0");
        const filename = `${y}-${m}-${d}.md`;
        fs.mkdirSync(channel.dir, { recursive: true });
        const filePath = path.join(channel.dir, filename);
        const existing = fs.existsSync(filePath)
          ? `${fs.readFileSync(filePath, "utf8")}\n\n---\n\n`
          : "";
        fs.writeFileSync(filePath, `${existing}${markdown}`, "utf8");
        log.info(`Digest written to ${filePath}`);
      } else if (channel.kind === "log") {
        log.info(`Daily digest\n${markdown}`);
      } else if (channel.kind === "message") {
        await channel.send(markdown);
      }
    } catch (err) {
      log.warn(
        `Digest delivery failed for ${channel.kind} channel: ${
          err instanceof Error ? err.message : String(err)
        }`,
      );
    }
  }
}
