#!/usr/bin/env node
/**
 * Version sync (PLAN-41 D-A). release-please bumps the ROOT package.json;
 * this script fans the version out to every other surface that carries
 * one, so nothing drifts:
 *
 *   - desktop/package.json
 *   - extensions/<*>/package.json (every extension that declares a version)
 *   - desktop/src-tauri/tauri.conf.json
 *   - desktop/src-tauri/Cargo.toml + Cargo.lock (bitterbot-desktop entry)
 *   - .release-please-manifest.json (kept in step when run manually)
 *
 * The README version badge is dynamic (shields.io reads the GitHub
 * release), so nothing in README.md is rewritten.
 *
 * Usage:
 *   node scripts/bump-version.mjs           # sync everything to root version
 *   node scripts/bump-version.mjs 1.0.0     # set root + sync everything
 *
 * The Control UI sidebar reads the version at build time (vite define),
 * so it needs no rewriting here.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function writeJson(file, data) {
  fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`);
}

const rootPkgPath = path.join(ROOT, "package.json");
const rootPkg = readJson(rootPkgPath);

const requested = process.argv[2]?.trim();
if (requested && !/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(requested)) {
  console.error(`bump-version: "${requested}" is not a valid version`);
  process.exit(1);
}
const version = requested || rootPkg.version;

const changed = [];

if (rootPkg.version !== version) {
  rootPkg.version = version;
  writeJson(rootPkgPath, rootPkg);
  changed.push("package.json");
}

// desktop
const desktopPkgPath = path.join(ROOT, "desktop", "package.json");
if (fs.existsSync(desktopPkgPath)) {
  const pkg = readJson(desktopPkgPath);
  if (pkg.version !== version) {
    pkg.version = version;
    writeJson(desktopPkgPath, pkg);
    changed.push("desktop/package.json");
  }
}

// extensions
const extRoot = path.join(ROOT, "extensions");
for (const entry of fs.readdirSync(extRoot, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const pkgPath = path.join(extRoot, entry.name, "package.json");
  if (!fs.existsSync(pkgPath)) continue;
  const pkg = readJson(pkgPath);
  if (pkg.version !== undefined && pkg.version !== version) {
    pkg.version = version;
    writeJson(pkgPath, pkg);
    changed.push(`extensions/${entry.name}/package.json`);
  }
}

// tauri
const tauriConfPath = path.join(ROOT, "desktop", "src-tauri", "tauri.conf.json");
if (fs.existsSync(tauriConfPath)) {
  const conf = readJson(tauriConfPath);
  if (conf.version !== undefined && conf.version !== version) {
    conf.version = version;
    writeJson(tauriConfPath, conf);
    changed.push("desktop/src-tauri/tauri.conf.json");
  }
}

// desktop Cargo.toml ([package] version is the first `version = ` line) and
// Cargo.lock (the [[package]] entry for bitterbot-desktop). release-please
// updates the .toml through extra-files; the lockfile is regenerated by
// `cargo build`, so a manual sync keeps the version-consistency test green
// on machines without cargo.
const cargoTomlPath = path.join(ROOT, "desktop", "src-tauri", "Cargo.toml");
if (fs.existsSync(cargoTomlPath)) {
  const toml = fs.readFileSync(cargoTomlPath, "utf8");
  const next = toml.replace(/^(\s*version\s*=\s*")[^"]+(")/m, `$1${version}$2`);
  if (next !== toml) {
    fs.writeFileSync(cargoTomlPath, next);
    changed.push("desktop/src-tauri/Cargo.toml");
  }
}
const cargoLockPath = path.join(ROOT, "desktop", "src-tauri", "Cargo.lock");
if (fs.existsSync(cargoLockPath)) {
  const lock = fs.readFileSync(cargoLockPath, "utf8");
  const next = lock.replace(
    /(\[\[package\]\]\s*\nname = "bitterbot-desktop"\s*\nversion = ")[^"]+(")/,
    `$1${version}$2`,
  );
  if (next !== lock) {
    fs.writeFileSync(cargoLockPath, next);
    changed.push("desktop/src-tauri/Cargo.lock");
  }
}

// release-please manifest (manual runs; the action maintains it on its own)
const manifestPath = path.join(ROOT, ".release-please-manifest.json");
if (fs.existsSync(manifestPath)) {
  const manifest = readJson(manifestPath);
  if (manifest["."] !== version) {
    manifest["."] = version;
    writeJson(manifestPath, manifest);
    changed.push(".release-please-manifest.json");
  }
}

if (changed.length === 0) {
  console.log(`bump-version: everything already at ${version}`);
} else {
  console.log(`bump-version: ${version} →\n  ${changed.join("\n  ")}`);
}
