/**
 * Write `<repoRoot>/desktop/.env` so the Control UI boots with a working
 * gateway token + URL already wired in.
 *
 * Context: the Control UI is a Vite SPA under `desktop/` that reads
 * VITE_GATEWAY_URL and VITE_GATEWAY_TOKEN from `desktop/.env` at build
 * time. Without it, the UI loads but shows "Disconnected" — which was the
 * single biggest friction point in the wizard: README and wizard both
 * claimed this file was auto-generated, but nothing actually wrote it.
 *
 * What this does:
 *   1. Resolve the repo root (only applicable when Bitterbot is run from
 *      a clone, not a global npm install — we skip cleanly if `desktop/`
 *      isn't present)
 *   2. If `desktop/.env` exists, update only VITE_GATEWAY_URL and
 *      VITE_GATEWAY_TOKEN (preserve any user customizations like client
 *      name or custom dev overrides)
 *   3. If not, write a fresh file with a header + the three standard vars
 */

import fs from "node:fs/promises";
import path from "node:path";
import type { GatewayWizardSettings } from "./onboarding.types.js";
import { resolveBitterbotPackageRoot } from "../infra/bitterbot-root.js";

export type ControlUiEnvWriteResult =
  | { ok: true; path: string; created: boolean }
  | { ok: false; reason: "no-repo" | "no-desktop-dir" | "write-failed"; detail?: string };

const HEADER = [
  "# Auto-generated by `bitterbot onboard` — re-runs preserve custom lines.",
  "# Gateway WebSocket URL + token for the Control UI (Vite SPA).",
  "",
].join("\n");

function setOrInsertLine(body: string, key: string, value: string): string {
  const safeValue = value.replace(/\r?\n/g, " ").trim();
  const line = `${key}=${safeValue}`;
  const lineRe = new RegExp(`^${key}=.*$`, "m");
  if (lineRe.test(body)) {
    return body.replace(lineRe, line);
  }
  const trimmed = body.replace(/\n+$/, "");
  return `${trimmed}\n${line}\n`;
}

export async function writeControlUiEnv(params: {
  settings: GatewayWizardSettings;
  moduleUrl: string;
}): Promise<ControlUiEnvWriteResult> {
  const { settings, moduleUrl } = params;

  const repoRoot = await resolveBitterbotPackageRoot({
    moduleUrl,
    argv1: process.argv[1],
    cwd: process.cwd(),
  });
  if (!repoRoot) {
    return { ok: false, reason: "no-repo" };
  }

  const desktopDir = path.join(repoRoot, "desktop");
  try {
    const stat = await fs.stat(desktopDir);
    if (!stat.isDirectory()) {
      return { ok: false, reason: "no-desktop-dir" };
    }
  } catch {
    // `desktop/` not present — likely a global npm install without the
    // Control UI workspace. Nothing to do; the wizard will surface the
    // gateway URL + token verbally.
    return { ok: false, reason: "no-desktop-dir" };
  }

  const envPath = path.join(desktopDir, ".env");
  const gatewayUrl = `ws://127.0.0.1:${settings.port}`;
  const token = settings.authMode === "token" ? (settings.gatewayToken ?? "") : "";

  let existing: string | null = null;
  try {
    existing = await fs.readFile(envPath, "utf8");
  } catch {
    // doesn't exist — we'll create fresh
  }

  let body: string;
  if (existing === null) {
    body =
      HEADER +
      `VITE_GATEWAY_URL=${gatewayUrl}\n` +
      `VITE_GATEWAY_TOKEN=${token}\n` +
      `VITE_GATEWAY_CLIENT_NAME=bitterbot-control-ui\n`;
  } else {
    body = setOrInsertLine(existing, "VITE_GATEWAY_URL", gatewayUrl);
    body = setOrInsertLine(body, "VITE_GATEWAY_TOKEN", token);
  }

  try {
    await fs.writeFile(envPath, body, { mode: 0o600 });
  } catch (err) {
    return {
      ok: false,
      reason: "write-failed",
      detail: err instanceof Error ? err.message : String(err),
    };
  }

  return { ok: true, path: envPath, created: existing === null };
}
