import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// PLAN-56 Phase 0 ("one version"): the root package.json is the single
// source of truth and release-please fans the bump out through
// `extra-files` in release-please-config.json. Every file that carries a
// copy of the version is listed here so a new one that is forgotten in
// the release config fails CI instead of drifting for a few releases
// (desktop/src-tauri/Cargo.toml sat at 0.1.0 and extensions/email at
// 1.2.0 while the product was 1.4.0).

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function readJson(rel: string): Record<string, unknown> {
  return JSON.parse(fs.readFileSync(path.join(ROOT, rel), "utf8")) as Record<string, unknown>;
}

function readText(rel: string): string {
  return fs.readFileSync(path.join(ROOT, rel), "utf8");
}

function cargoPackageVersion(rel: string): string | undefined {
  // First `version = "x.y.z"` line: Cargo.toml opens with [package].
  return /^\s*version\s*=\s*"([^"]+)"/m.exec(readText(rel))?.[1];
}

function cargoLockPackageVersion(rel: string, name: string): string | undefined {
  const re = new RegExp(`\\[\\[package\\]\\]\\s*\\nname = "${name}"\\s*\\nversion = "([^"]+)"`);
  return re.exec(readText(rel))?.[1];
}

function listExtensionManifests(): string[] {
  const dir = path.join(ROOT, "extensions");
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => `extensions/${entry.name}/package.json`)
    .filter((rel) => fs.existsSync(path.join(ROOT, rel)))
    .toSorted();
}

const rootVersion = readJson("package.json").version as string;

describe("version consistency", () => {
  it("root package.json carries a semver version", () => {
    expect(rootVersion).toMatch(/^\d+\.\d+\.\d+(-[\w.]+)?$/);
  });

  const versionBearingFiles: Array<[string, () => string | undefined]> = [
    ["desktop/package.json", () => readJson("desktop/package.json").version as string],
    [
      "desktop/src-tauri/tauri.conf.json",
      () => readJson("desktop/src-tauri/tauri.conf.json").version as string,
    ],
    ["desktop/src-tauri/Cargo.toml", () => cargoPackageVersion("desktop/src-tauri/Cargo.toml")],
    [
      "desktop/src-tauri/Cargo.lock",
      () => cargoLockPackageVersion("desktop/src-tauri/Cargo.lock", "bitterbot-desktop"),
    ],
    [
      ".release-please-manifest.json",
      () => readJson(".release-please-manifest.json")["."] as string,
    ],
    ...listExtensionManifests()
      .filter((rel) => readJson(rel).version !== undefined)
      .map((rel): [string, () => string | undefined] => [
        rel,
        () => readJson(rel).version as string,
      ]),
  ];

  for (const [rel, read] of versionBearingFiles) {
    it(`${rel} matches package.json (${rootVersion})`, () => {
      expect(read(), `${rel} version`).toBe(rootVersion);
    });
  }

  it("release-please-config.json fans the bump out to every versioned file", () => {
    const config = readJson("release-please-config.json") as {
      packages: Record<string, { "extra-files"?: Array<{ path: string }> }>;
    };
    const extraPaths = new Set((config.packages["."]["extra-files"] ?? []).map((f) => f.path));
    const expected = versionBearingFiles
      .map(([rel]) => rel)
      // The manifest is maintained by release-please itself; Cargo.lock is
      // regenerated by `cargo build` and synced by scripts/bump-version.mjs.
      .filter((rel) => rel !== ".release-please-manifest.json")
      .filter((rel) => rel !== "desktop/src-tauri/Cargo.lock");
    for (const rel of expected) {
      expect(extraPaths.has(rel), `${rel} missing from release-please extra-files`).toBe(true);
    }
  });
});
